### ISSUE TITLE
"x" says "y"! test fails when encountering Vietnamese

### ISSUE THREAD

**Issue by JacobJenness** [UMM-CSci-3601-S21/intro-to-git-S21#28] opened 2021-01-28 17:48 UTC
In the current build, one of the lines printed is `Elena says 'Xin chào!`. The test that determines if this is in the right form incorrectly says that it's not in the right form. 

> `org.opentest4j.AssertionFailedError: Line <Elena says 'Xin chÃ o!'> doesn't match pattern '<Name> says <greeting>!' ==> expected: <true> but was: <false>` This was the first line in `index.html`

It appears that the character `à` is the problem here for some reason.

**Comment by NicMcPhee** [comment] 2021-01-28 18:10
I'm confused here. This passes for me (with Elena's code in there), and [it passes here on GitHub](https://github.com/UMM-CSci-3601-S21/intro-to-git-S21/runs/1785964138). In what way does it not pass for you?

**Comment by JacobJenness** [comment] 2021-01-28 18:25
When I run `./gradlew check` in VS Code it gives me an error for the `testLineStructure` test at line 30. I know for a fact that if the character `à` is removed it will pass. No idea why it happens though.

**Comment by helloworld12321** [comment] 2021-01-28 21:21
@JacobJenness That's helpful, thank you!

**Comment by JacobJenness** [comment] 2021-01-31 00:21
This issue has been fixed, and the tests now pass on my Windows machine.

**Comment by helloworld12321** [comment] 2021-01-31 01:42
@JacobJenness, I'm glad to hear that the issue is fixed! Thanks for all your help in diagnosing it.

I'm actually going to keep this PR open just for a little while longer, since the PR fixing it (#29) hasn't quite been merged into `main` yet.

(In fact, since I've [linked this issue](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) to PR #29, merging that pull request will close this issue automatically! ☺️)

(Sorry, it's very thoughtful of you to keep the GitHub issues up to date like this, and I'm sorry for undoing your work—I just thought this would be a good Learning Moment™ 🙃)

**Comment by helloworld12321** [comment] 2021-01-31 01:43
Okay, now I'm going to go merge #29 :)

**Closed as completed** 2021-01-31 01:44 UTC
